<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>2.0.0-local</Version>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(CI)' == 'true'">true</RestoreLockedMode>
    <Authors>devRael1</Authors>
    <Company>TorBox</Company>
    <Copyright>Copyright © 2026 devRael1</Copyright>
  </PropertyGroup>
</Project>
